version: "3.4"
services:
  frontend-service:
    container_name: tafsiri_frontend
    build:
      context: ./tafsiri_frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      #- './admin:/app'
      - '/app/node_modules'
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
